Repository arpy8/HackProjects, pull requests merged in 2024-10, with the labels that each got.

#3 Create Dockerfile for server side script, completes #2
  server/Dockerfile
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#4 add readme file for server
  server/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#5 update primary color
  app/contact/page.tsx
  app/dashboard/layout.tsx
  app/globals.css
Labels: hacktoberfest, hacktoberfest-accepted

#6 remove overview
  app/dashboard/overview/overview.tsx
Labels: hacktoberfest, hacktoberfest-accepted
